version: '3'

services:
  apisix-admin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: apisix-admin
    restart: "always"
    volumes:
      - /var/log/apisix-admin/:/var/log/apisix-admin/
      - ./config/apisix-admin.toml:/app/config/apisix-admin.toml
      - ./apisix-admin:/app/apisix-admin
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
    command: ["-c", "/app/config/apisix-admin.toml"]
    ports:
      - 9101:9002

