// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: pb/apisix.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	CreateTime  int64    `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	RemoteAddrs []string `protobuf:"bytes,3,rep,name=remote_addrs,json=remoteAddrs,proto3" json:"remote_addrs"`
	UpdateTime  int64    `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time"`
	Uri         string   `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri"`
	Uris        []string `protobuf:"bytes,6,rep,name=uris,proto3" json:"uris"`
	UpstreamId  string   `protobuf:"bytes,7,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id"`
	Desc        string   `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc"`
	Hosts       []string `protobuf:"bytes,9,rep,name=hosts,proto3" json:"hosts"`
	Methods     []string `protobuf:"bytes,10,rep,name=methods,proto3" json:"methods"`
}

func (x *RouteValue) Reset() {
	*x = RouteValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteValue) ProtoMessage() {}

func (x *RouteValue) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteValue.ProtoReflect.Descriptor instead.
func (*RouteValue) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{0}
}

func (x *RouteValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteValue) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RouteValue) GetRemoteAddrs() []string {
	if x != nil {
		return x.RemoteAddrs
	}
	return nil
}

func (x *RouteValue) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *RouteValue) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RouteValue) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *RouteValue) GetUpstreamId() string {
	if x != nil {
		return x.UpstreamId
	}
	return ""
}

func (x *RouteValue) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *RouteValue) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *RouteValue) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type RouteNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value *RouteValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
}

func (x *RouteNodes) Reset() {
	*x = RouteNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteNodes) ProtoMessage() {}

func (x *RouteNodes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteNodes.ProtoReflect.Descriptor instead.
func (*RouteNodes) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{1}
}

func (x *RouteNodes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RouteNodes) GetValue() *RouteValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type RouteNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Nodes []*RouteNodes `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes"`
}

func (x *RouteNode) Reset() {
	*x = RouteNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteNode) ProtoMessage() {}

func (x *RouteNode) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteNode.ProtoReflect.Descriptor instead.
func (*RouteNode) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{2}
}

func (x *RouteNode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RouteNode) GetNodes() []*RouteNodes {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListRouteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   string     `protobuf:"bytes,1,opt,name=action,proto3" json:"action"`
	Count    int32      `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	Node     *RouteNode `protobuf:"bytes,3,opt,name=node,proto3" json:"node"`
	ErrorMsg string     `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg"`
}

func (x *ListRouteResp) Reset() {
	*x = ListRouteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRouteResp) ProtoMessage() {}

func (x *ListRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRouteResp.ProtoReflect.Descriptor instead.
func (*ListRouteResp) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{3}
}

func (x *ListRouteResp) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListRouteResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListRouteResp) GetNode() *RouteNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ListRouteResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Uris        []string `protobuf:"bytes,2,rep,name=uris,proto3" json:"uris"`
	Uri         string   `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri"`
	Hosts       []string `protobuf:"bytes,4,rep,name=hosts,proto3" json:"hosts"`
	Name        string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Desc        string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc"`
	RemoteAddrs []string `protobuf:"bytes,7,rep,name=remote_addrs,json=remoteAddrs,proto3" json:"remote_addrs"`
	UpstreamId  string   `protobuf:"bytes,8,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id"`
	Methods     []string `protobuf:"bytes,9,rep,name=methods,proto3" json:"methods"`
}

func (x *CreateRouteReq) Reset() {
	*x = CreateRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteReq) ProtoMessage() {}

func (x *CreateRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteReq.ProtoReflect.Descriptor instead.
func (*CreateRouteReq) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRouteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRouteReq) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *CreateRouteReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CreateRouteReq) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *CreateRouteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRouteReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateRouteReq) GetRemoteAddrs() []string {
	if x != nil {
		return x.RemoteAddrs
	}
	return nil
}

func (x *CreateRouteReq) GetUpstreamId() string {
	if x != nil {
		return x.UpstreamId
	}
	return ""
}

func (x *CreateRouteReq) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type CreateRouteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   string     `protobuf:"bytes,1,opt,name=action,proto3" json:"action"`
	Node     *RouteNode `protobuf:"bytes,2,opt,name=node,proto3" json:"node"`
	ErrorMsg string     `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg"`
}

func (x *CreateRouteResp) Reset() {
	*x = CreateRouteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteResp) ProtoMessage() {}

func (x *CreateRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteResp.ProtoReflect.Descriptor instead.
func (*CreateRouteResp) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRouteResp) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateRouteResp) GetNode() *RouteNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *CreateRouteResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted  string `protobuf:"bytes,1,opt,name=deleted,proto3" json:"deleted"`
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key"`
	Action   string `protobuf:"bytes,3,opt,name=action,proto3" json:"action"`
	ErrorMsg string `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg"`
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResp) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

func (x *DeleteResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteResp) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DeleteResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type UpstreamValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme     string           `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme"`
	Type       string           `protobuf:"bytes,2,opt,name=type,proto3" json:"type"`
	UpdateTime int64            `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time"`
	PassHost   string           `protobuf:"bytes,4,opt,name=pass_host,json=passHost,proto3" json:"pass_host"`
	Nodes      map[string]int32 `protobuf:"bytes,5,rep,name=nodes,proto3" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" json:"nodes"`
	Id         string           `protobuf:"bytes,6,opt,name=id,proto3" json:"id"`
	CreateTime int64            `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	HashOn     string           `protobuf:"bytes,8,opt,name=hash_on,json=hashOn,proto3" json:"hash_on"`
	Desc       string           `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc"`
	Name       string           `protobuf:"bytes,10,opt,name=name,proto3" json:"name"`
}

func (x *UpstreamValue) Reset() {
	*x = UpstreamValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpstreamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamValue) ProtoMessage() {}

func (x *UpstreamValue) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamValue.ProtoReflect.Descriptor instead.
func (*UpstreamValue) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{8}
}

func (x *UpstreamValue) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *UpstreamValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpstreamValue) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UpstreamValue) GetPassHost() string {
	if x != nil {
		return x.PassHost
	}
	return ""
}

func (x *UpstreamValue) GetNodes() map[string]int32 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *UpstreamValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpstreamValue) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UpstreamValue) GetHashOn() string {
	if x != nil {
		return x.HashOn
	}
	return ""
}

func (x *UpstreamValue) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpstreamValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpstreamNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string         `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value *UpstreamValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
}

func (x *UpstreamNodes) Reset() {
	*x = UpstreamNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpstreamNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamNodes) ProtoMessage() {}

func (x *UpstreamNodes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamNodes.ProtoReflect.Descriptor instead.
func (*UpstreamNodes) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{9}
}

func (x *UpstreamNodes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpstreamNodes) GetValue() *UpstreamValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type UpstreamNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Nodes []*UpstreamNodes `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes"`
}

func (x *UpstreamNode) Reset() {
	*x = UpstreamNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpstreamNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamNode) ProtoMessage() {}

func (x *UpstreamNode) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamNode.ProtoReflect.Descriptor instead.
func (*UpstreamNode) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{10}
}

func (x *UpstreamNode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpstreamNode) GetNodes() []*UpstreamNodes {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" form:"page"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size" form:"size"`
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{11}
}

func (x *ListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListUpstreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string        `protobuf:"bytes,1,opt,name=action,proto3" json:"action"`
	Node   *UpstreamNode `protobuf:"bytes,2,opt,name=node,proto3" json:"node"`
	Count  int32         `protobuf:"varint,3,opt,name=count,proto3" json:"count"`
}

func (x *ListUpstreamResp) Reset() {
	*x = ListUpstreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUpstreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpstreamResp) ProtoMessage() {}

func (x *ListUpstreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpstreamResp.ProtoReflect.Descriptor instead.
func (*ListUpstreamResp) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{12}
}

func (x *ListUpstreamResp) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListUpstreamResp) GetNode() *UpstreamNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ListUpstreamResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateUpstreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Nodes map[string]int32 `protobuf:"bytes,2,rep,name=nodes,proto3" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" json:"nodes"`
	Name  string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Desc  string           `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc"`
	Type  string           `protobuf:"bytes,5,opt,name=type,proto3" json:"type"`
}

func (x *CreateUpstreamReq) Reset() {
	*x = CreateUpstreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUpstreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpstreamReq) ProtoMessage() {}

func (x *CreateUpstreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpstreamReq.ProtoReflect.Descriptor instead.
func (*CreateUpstreamReq) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUpstreamReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUpstreamReq) GetNodes() map[string]int32 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CreateUpstreamReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUpstreamReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateUpstreamReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateUpstreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string         `protobuf:"bytes,1,opt,name=action,proto3" json:"action"`
	Node   *UpstreamNodes `protobuf:"bytes,2,opt,name=node,proto3" json:"node"`
}

func (x *CreateUpstreamResp) Reset() {
	*x = CreateUpstreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_apisix_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUpstreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpstreamResp) ProtoMessage() {}

func (x *CreateUpstreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apisix_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpstreamResp.ProtoReflect.Descriptor instead.
func (*CreateUpstreamResp) Descriptor() ([]byte, []int) {
	return file_pb_apisix_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUpstreamResp) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateUpstreamResp) GetNode() *UpstreamNodes {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_pb_apisix_proto protoreflect.FileDescriptor

var file_pb_apisix_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x22, 0x8c, 0x02, 0x0a, 0x0a, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x72, 0x69, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x72, 0x69, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x47, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x28, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x81, 0x01, 0x0a, 0x0d,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x73,
	0x69, 0x78, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0xe2, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x69, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x72, 0x69, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x22, 0x6d, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x25, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x1b, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x6d, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0xdd, 0x02, 0x0a, 0x0d, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x73, 0x69, 0x78, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x6f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x4f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x38, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x4e, 0x0a, 0x0d, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x4d, 0x0a, 0x0c, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x2b, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x31,
	0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x22, 0x6a, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70,
	0x69, 0x73, 0x69, 0x78, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xd5, 0x01,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x38, 0x0a, 0x0a, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x57, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x42, 0x1e,
	0x5a, 0x1c, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_apisix_proto_rawDescOnce sync.Once
	file_pb_apisix_proto_rawDescData = file_pb_apisix_proto_rawDesc
)

func file_pb_apisix_proto_rawDescGZIP() []byte {
	file_pb_apisix_proto_rawDescOnce.Do(func() {
		file_pb_apisix_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_apisix_proto_rawDescData)
	})
	return file_pb_apisix_proto_rawDescData
}

var file_pb_apisix_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pb_apisix_proto_goTypes = []interface{}{
	(*RouteValue)(nil),         // 0: apisix.RouteValue
	(*RouteNodes)(nil),         // 1: apisix.RouteNodes
	(*RouteNode)(nil),          // 2: apisix.RouteNode
	(*ListRouteResp)(nil),      // 3: apisix.ListRouteResp
	(*CreateRouteReq)(nil),     // 4: apisix.CreateRouteReq
	(*CreateRouteResp)(nil),    // 5: apisix.CreateRouteResp
	(*DeleteReq)(nil),          // 6: apisix.DeleteReq
	(*DeleteResp)(nil),         // 7: apisix.DeleteResp
	(*UpstreamValue)(nil),      // 8: apisix.UpstreamValue
	(*UpstreamNodes)(nil),      // 9: apisix.UpstreamNodes
	(*UpstreamNode)(nil),       // 10: apisix.UpstreamNode
	(*ListReq)(nil),            // 11: apisix.ListReq
	(*ListUpstreamResp)(nil),   // 12: apisix.ListUpstreamResp
	(*CreateUpstreamReq)(nil),  // 13: apisix.CreateUpstreamReq
	(*CreateUpstreamResp)(nil), // 14: apisix.CreateUpstreamResp
	nil,                        // 15: apisix.UpstreamValue.NodesEntry
	nil,                        // 16: apisix.CreateUpstreamReq.NodesEntry
}
var file_pb_apisix_proto_depIdxs = []int32{
	0,  // 0: apisix.RouteNodes.value:type_name -> apisix.RouteValue
	1,  // 1: apisix.RouteNode.nodes:type_name -> apisix.RouteNodes
	2,  // 2: apisix.ListRouteResp.node:type_name -> apisix.RouteNode
	2,  // 3: apisix.CreateRouteResp.node:type_name -> apisix.RouteNode
	15, // 4: apisix.UpstreamValue.nodes:type_name -> apisix.UpstreamValue.NodesEntry
	8,  // 5: apisix.UpstreamNodes.value:type_name -> apisix.UpstreamValue
	9,  // 6: apisix.UpstreamNode.nodes:type_name -> apisix.UpstreamNodes
	10, // 7: apisix.ListUpstreamResp.node:type_name -> apisix.UpstreamNode
	16, // 8: apisix.CreateUpstreamReq.nodes:type_name -> apisix.CreateUpstreamReq.NodesEntry
	9,  // 9: apisix.CreateUpstreamResp.node:type_name -> apisix.UpstreamNodes
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pb_apisix_proto_init() }
func file_pb_apisix_proto_init() {
	if File_pb_apisix_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_apisix_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRouteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRouteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpstreamValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpstreamNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpstreamNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUpstreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUpstreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_apisix_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUpstreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_apisix_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_apisix_proto_goTypes,
		DependencyIndexes: file_pb_apisix_proto_depIdxs,
		MessageInfos:      file_pb_apisix_proto_msgTypes,
	}.Build()
	File_pb_apisix_proto = out.File
	file_pb_apisix_proto_rawDesc = nil
	file_pb_apisix_proto_goTypes = nil
	file_pb_apisix_proto_depIdxs = nil
}
